/*
 * Denis Novac
 * 2017
 *
 * Autogenerated database powered by H2.
 *
 */

package org.novac;

import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;

public class DatabaseH2 {
	private String databasePath = "jdbc:h2:./data/";
	private String user = "user";
	private String password = "";

	public DatabaseH2 (String name) {
		name=name.trim();
		databasePath+=name;
		try {
			Class.forName("org.h2.Driver");
			Connection conn = DriverManager.getConnection(
				databasePath, user, password);
			Statement st = conn.createStatement();
			st.execute("CREATE TABLE users( userid int, username varchar(255) )");
			st.execute("INSERT INTO users (userid,username) VALUES (1,'denis')");
			st.execute("INSERT INTO users (userid,username) VALUES (2,'fil')");

			ResultSet results = st.executeQuery("SELECT userid, username FROM users");
			while (results.next()) {
				String userid = results.getString("userid");
				String username = results.getString("username");
				System.out.println(userid+" "+username);
			}

			conn.close();
		} catch (Exception e) {
			System.out.println(e);
		}
	}



}